### ISSUE TITLE
Request: KVM support (VM)

### ISSUE THREAD

**Issue by fsoc137y777** [tracelabs/tlosint-vm#24]
Can you add support for KVM?

https://www.linux-kvm.org/page/Downloads

**Comment by mmuyskens** [comment]
The .ova format can be seen as basically a tar archive which when extracted contains an .ovf and a .vmdk files.

Once extracted, you can use qemu to convert;

# qemu-img convert -f vmdk input.vmdk -O qcow2 output.qcow2

The qcow2 image can then be used to create a KVM with.

**Comment by fsoc137y777** [comment]
thanks :) solved
