### ISSUE TITLE
TraceLabs silences the community

### ISSUE THREAD

**Issue by ryd3v** [tracelabs/tlosint-vm#44]
You @UlicBelouvehad mentioned you were sorry I feel this way... and without having the chance to respond, the feeling I currently have is a little perplexed to be honest with you. I had a good experience with TL in years past, as well as in the server. I also understand the dynamic of being a competitor, and the stress, that goes along with that. My issue currently is two fold. 

The first is the accusations, the details that stood out to me were, threats, verbal abuse, and bullying by the staff of @TraceLabs 

That is completely unacceptable, regardless of the accusations. 

From Heath, https://www.linkedin.com/posts/heathadams_i-truly-regret-having-to-make-this-post-activity-7125518074157404160-Qafi?utm_source=share&utm_medium=member_desktop

The accusations that led to this display of unprofessional behavior from @TraceLabs 

The accusations;
1) The judge went around both the night before and the day of, speaking negatively of me (and some of our teammates)
2) When the judge found out we were competing, he DM'd our team individually attempting to find our team name. After getting no response, he went to the TCM booth and tried again. While at the booth, he spoke negatively of me to my wife and teammates (many can attest to this). He eventually abused his powers and looked up our emails in the system to force his way into being our judge.
3) He took over as our judge 30 minutes into the competition. He then stopped grading our submissions a little over an hour after that. We did not receive another graded submission until after the competition was over

![Sceenshot](https://x.com/ryd3v/status/1722745260818702637?s=20)
![Screenshot from 2023-11-09 16-49-49](https://github.com/tracelabs/tlosint-vm/assets/81205911/2f109cf1-4675-4891-8518-682bb977c360)

**Comment by humandecoded** [comment]
Closing as this isn't an issue with this repo. contact@tracelabs.org would be the best place to direct this.
