### ISSUE TITLE
sn0int failing to build

### ISSUE THREAD

**Issue by 7069wrk** [tracelabs/tlosint-vm#61]
Installing sn0int v0.26.0 (/usr/share/sn0int)                                                    
    Updating crates.io index
error: failed to compile `sn0int v0.26.0 (/usr/share/sn0int)`, intermediate artifacts can be found at `/usr/share/sn0int/target`

Caused by:
  package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
  Either upgrade to rustc 1.74 or newer, or use
  cargo update -p clap@4.5.4 --precise ver
  where `ver` is the latest version of `clap` supporting rustc 1.70.0

**Comment by humandecoded** [comment]
should be fixed in current dev branch, will get pushed to main shortly

**Comment by humandecoded** [comment]
should have been fixed in https://github.com/tracelabs/tlosint-vm/releases/tag/2024.04
