### ISSUE TITLE
Regular build cycle tied to github action

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-vm#7]
It would be good to update the virtual machine image on a regular basis rather than just when we update the repository.

**Comment by xFreed0m** [comment]
you mean update and auto release new version? I prefer not to go the auto route, but maybe schedule a manual update and release every 6 months?

**Comment by sanecito** [comment]
I was about to express interest in contributing to an annual release at least since it looks like there was no image update for DC30 based on the blog posts.

**Comment by humandecoded** [comment]
I think is doable now that we've got the images  down to a size that Github is good with. Could now be as simple as pushing a release once a month (or whatever we want our build cycle to be)

**Comment by humandecoded** [comment]
think we are in a good place here. The github actions are working as intended
